
# Don't change unless you know what you are doing.
# Always keep a backup before changing anything.

backend = "full"
color_space = "lchmixed"
palette = "harddark16"
check_contrast = true
fallback_generator = "complementary"


[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ¡ If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }


cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty-themes/kitty-color.conf'

waybar.template = 'waybar.css'
waybar.target = '~/.config/waybar/wallust/waybar.css'

nvim.template = 'colors-wal.vim'
nvim.target = '~/.cache/wal/colors-wal.vim'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'

tofi.template = 'colors-tofi'
tofi.target = '~/.config/tofi/wallust/colors-tofi'

wlogout.template = 'colors-wlogout.css'
wlogout.target = '~/.config/wlogout/wallust/colors-wlogout.css'

gtk.template = 'gtk-color.css'
gtk.target = '~/.config/gtk-4.0/wallust/gtk-color.css'

gtk3.template = 'gtk-color.css'
gtk3.target = '~/.config/gtk-3.0/wallust/gtk-color.css'
