# Image Path
$image = /home/levi/Pictures/Wallpapers/d1P6xtd.jpeg

# An alpha background
$surface_alpha = rgba(1721264d)

# All Colors
  $background = rgba(172126ff)
  $error = rgba(fd4663ff)
  $error_container = rgba(900017ff)
  $inverse_on_surface = rgba(242828ff)
  $inverse_primary = rgba(338a99ff)
  $inverse_surface = rgba(e3e7e8ff)
  $on_background = rgba(f2f3f3ff)
  $on_error = rgba(182325ff)
  $on_error_container = rgba(fecdd4ff)
  $on_primary = rgba(182325ff)
  $on_primary_container = rgba(edf4f5ff)
  $on_primary_fixed = rgba(212a2cff)
  $on_primary_fixed_variant = rgba(2b383bff)
  $on_secondary = rgba(182325ff)
  $on_secondary_container = rgba(dfe4ecff)
  $on_secondary_fixed = rgba(21242cff)
  $on_secondary_fixed_variant = rgba(2b313bff)
  $on_surface = rgba(f2f3f3ff)
  $on_surface_variant = rgba(afb5b6ff)
  $on_tertiary = rgba(182325ff)
  $on_tertiary_container = rgba(e1dfecff)
  $on_tertiary_fixed = rgba(22212cff)
  $on_tertiary_fixed_variant = rgba(2e2b3bff)
  $outline = rgba(5b6d6fff)
  $outline_variant = rgba(5c6d70ff)
  $primary = rgba(67d2e4ff)
  $primary_container = rgba(0c7a8dff)
  $primary_fixed = rgba(beecf4ff)
  $primary_fixed_dim = rgba(93dfecff)
  $scrim = rgba(000000ff)
  $secondary = rgba(5c85d6ff)
  $secondary_container = rgba(10306fff)
  $secondary_fixed = rgba(bed0f4ff)
  $secondary_fixed_dim = rgba(96b2e9ff)
  $shadow = rgba(172126ff)
  $surface = rgba(172126ff)
  $surface_bright = rgba(2e434cff)
  $surface_container = rgba(263840ff)
  $surface_container_high = rgba(233239ff)
  $surface_container_highest = rgba(2a3d46ff)
  $surface_container_low = rgba(131c20ff)
  $surface_container_lowest = rgba(0c1113ff)
  $surface_dim = rgba(0f1619ff)
  $surface_tint = rgba(67d2e4ff)
  $surface_variant = rgba(1f2c33ff)
  $tertiary = rgba(7566ccff)
  $tertiary_container = rgba(221669ff)
  $tertiary_fixed = rgba(c6bef4ff)
  $tertiary_fixed_dim = rgba(a296e9ff)
