# Image Path
$image = /home/levi/Pictures/Wallpapers/cat-mocha-peach_6.jpg

# An alpha background
$surface_alpha = rgba(291a144d)

# All Colors
  $background = rgba(291a14ff)
  $error = rgba(fc7a47ff)
  $error_container = rgba(902900ff)
  $inverse_on_surface = rgba(282524ff)
  $inverse_primary = rgba(b54417ff)
  $inverse_surface = rgba(e8e5e3ff)
  $on_background = rgba(f3f2f2ff)
  $on_error = rgba(191311ff)
  $on_error_container = rgba(fedbcdff)
  $on_primary = rgba(1f1714ff)
  $on_primary_container = rgba(fedbcdff)
  $on_primary_fixed = rgba(2c2421ff)
  $on_primary_fixed_variant = rgba(3b302bff)
  $on_secondary = rgba(251c18ff)
  $on_secondary_container = rgba(fffcf3ff)
  $on_secondary_fixed = rgba(2c2921ff)
  $on_secondary_fixed_variant = rgba(3b372bff)
  $on_surface = rgba(f3f2f2ff)
  $on_surface_variant = rgba(b6b1afff)
  $on_tertiary = rgba(251c18ff)
  $on_tertiary_container = rgba(f0fecdff)
  $on_tertiary_fixed = rgba(292c21ff)
  $on_tertiary_fixed_variant = rgba(363b2bff)
  $outline = rgba(74655fff)
  $outline_variant = rgba(74655fff)
  $primary = rgba(fc804fff)
  $primary_container = rgba(992b00ff)
  $primary_fixed = rgba(fec9b4ff)
  $primary_fixed_dim = rgba(fda582ff)
  $scrim = rgba(000000ff)
  $secondary = rgba(fcd447ff)
  $secondary_container = rgba(907100ff)
  $secondary_fixed = rgba(feedb4ff)
  $secondary_fixed_dim = rgba(fde282ff)
  $shadow = rgba(291a14ff)
  $surface = rgba(291a14ff)
  $surface_bright = rgba(533428ff)
  $surface_container = rgba(452b21ff)
  $surface_container_high = rgba(3e271eff)
  $surface_container_highest = rgba(4c3025ff)
  $surface_container_low = rgba(221611ff)
  $surface_container_lowest = rgba(150d0aff)
  $surface_dim = rgba(1c110dff)
  $surface_tint = rgba(fc804fff)
  $surface_variant = rgba(37231bff)
  $tertiary = rgba(c9fc47ff)
  $tertiary_container = rgba(689000ff)
  $tertiary_fixed = rgba(e9feb4ff)
  $tertiary_fixed_dim = rgba(dafd82ff)
