# Image Path
$image = /home/levi/Pictures/Wallpapers/cat-mocha-peach_6.jpg

# An alpha background
$surface_alpha = rgba(291e144d)

# All Colors
  $background = rgba(291e14ff)
  $error = rgba(ff9e4cff)
  $error_container = rgba(994600ff)
  $inverse_on_surface = rgba(282624ff)
  $inverse_primary = rgba(b85f14ff)
  $inverse_surface = rgba(e8e5e3ff)
  $on_background = rgba(f3f2f2ff)
  $on_error = rgba(251e18ff)
  $on_error_container = rgba(ffe3ccff)
  $on_primary = rgba(251e18ff)
  $on_primary_container = rgba(ffe3ccff)
  $on_primary_fixed = rgba(2c2621ff)
  $on_primary_fixed_variant = rgba(3b322bff)
  $on_secondary = rgba(251e18ff)
  $on_secondary_container = rgba(fffdccff)
  $on_secondary_fixed = rgba(2c2c21ff)
  $on_secondary_fixed_variant = rgba(3b3a2bff)
  $on_surface = rgba(f3f2f2ff)
  $on_surface_variant = rgba(b6b2afff)
  $on_tertiary = rgba(251e18ff)
  $on_tertiary_container = rgba(e8ffccff)
  $on_tertiary_fixed = rgba(272c21ff)
  $on_tertiary_fixed_variant = rgba(343b2bff)
  $outline = rgba(73685eff)
  $outline_variant = rgba(73685eff)
  $primary = rgba(ff9e4dff)
  $primary_container = rgba(9a4600ff)
  $primary_fixed = rgba(ffd5b2ff)
  $primary_fixed_dim = rgba(ffba80ff)
  $scrim = rgba(000000ff)
  $secondary = rgba(fff84cff)
  $secondary_container = rgba(999300ff)
  $secondary_fixed = rgba(fffcb2ff)
  $secondary_fixed_dim = rgba(fffa80ff)
  $shadow = rgba(291e14ff)
  $surface = rgba(291e14ff)
  $surface_bright = rgba(533c28ff)
  $surface_container = rgba(453221ff)
  $surface_container_high = rgba(3e2d1eff)
  $surface_container_highest = rgba(4c3725ff)
  $surface_container_low = rgba(221911ff)
  $surface_container_lowest = rgba(150f0aff)
  $surface_dim = rgba(1c140dff)
  $surface_tint = rgba(ff9e4dff)
  $surface_variant = rgba(37281bff)
  $tertiary = rgba(adff4cff)
  $tertiary_container = rgba(539900ff)
  $tertiary_fixed = rgba(dcffb2ff)
  $tertiary_fixed_dim = rgba(c5ff80ff)
