foreground         #ECE8E6
background         #242221
cursor             #B1B5B8

active_tab_foreground     #242221
active_tab_background     #ECE8E6
inactive_tab_foreground   #ECE8E6
inactive_tab_background   #242221

active_border_color   #ECE8E6
inactive_border_color #242221
bell_border_color     #675F59

color0      #3A3837
color1		#675F59
color2		#596167
color3		#76787C
color4		#7C7A76
color5		#7C7A76
color6		#968F8A
color7		#DBD6D3
color8		#999694
color9		#897E77
color10		#778289
color11		#9DA0A6
color12		#A6A39D
color13		#A6A39D
color14		#C8BEB8
color15		#DBD6D3
