color0 #291a14
color1 #fc7a47
color2 #fc804f
color3 #fcd447
color4 #c9fc47
color5 #fda582
color6 #fde282
color7 #f3f2f2
color8 #74655f
color9 #fc7a47
color10 #fc804f
color11 #fcd447
color12 #c9fc47
color13 #fda582
color14 #fde282
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291a14
background            #291a14
foreground            #f3f2f2
selection_foreground  #b6b1af
selection_background  #37231b
active_border_color   #fc804f
inactive_border_color #37231b
url_color             #fc804f
