color0 #291e14
color1 #ff9e4c
color2 #ff9e4d
color3 #fff84c
color4 #adff4c
color5 #ffba80
color6 #fffa80
color7 #f3f2f2
color8 #73685e
color9 #ff9e4c
color10 #ff9e4d
color11 #fff84c
color12 #adff4c
color13 #ffba80
color14 #fffa80
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291e14
background            #291e14
foreground            #f3f2f2
selection_foreground  #b6b2af
selection_background  #37281b
active_border_color   #ff9e4d
inactive_border_color #37281b
url_color             #ff9e4d
